name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: # 액션에 입력 파라미터를 넘김
          path: our-source
      - run: ls -al
      - run: ls -al our-source
      - run: cat our-source/.github/workflows/checkout.yml
